name: mirai_responsive
description: Responsive UI Package Created By Mirai Devs.
version: 0.0.1
homepage: https://github.com/devhch/mirai_responsive

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:
